vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<leader>e", "<cmd>Neotree toggle<CR>", { desc = "Toggle file explorer" })
vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })
vim.keymap.set("n", "<leader>w", "<cmd>w<CR>", { desc = "Save file" })
vim.keymap.set("n", "<leader>q", "<cmd>q<CR>", { desc = "Quit" })
vim.keymap.set("n", "<leader>x", "<cmd>x<CR>", { desc = "Save and quit" })
vim.keymap.set("n", "<leader>tt", "<cmd>TransparentToggle<CR>", { desc = "Toggle transparency" })

vim.keymap.set("n", "<leader>cc", "<cmd>ClaudeCode<CR>", { desc = "Claude: Chat" })
vim.keymap.set("v", "<leader>cc", "<cmd>ClaudeCode<CR>", { desc = "Claude: Chat with selection" })
vim.keymap.set("n", "<leader>ce", "<cmd>ClaudeCodeExplain<CR>", { desc = "Claude: Explain code" })
vim.keymap.set("v", "<leader>ce", "<cmd>ClaudeCodeExplain<CR>", { desc = "Claude: Explain selection" })
vim.keymap.set("n", "<leader>cr", "<cmd>ClaudeCodeReview<CR>", { desc = "Claude: Review code" })
vim.keymap.set("v", "<leader>cr", "<cmd>ClaudeCodeReview<CR>", { desc = "Claude: Review selection" })
vim.keymap.set("n", "<leader>ct", "<cmd>ClaudeCodeTest<CR>", { desc = "Claude: Generate tests" })
vim.keymap.set("v", "<leader>ct", "<cmd>ClaudeCodeTest<CR>", { desc = "Claude: Generate tests for selection" })